server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/santiagoforonda/AlmacenCarros
          search-paths: configdata
  application:
    name: Configserver